# Generated by Django 5.1.6 on 2025-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Registro de Log',
                'verbose_name_plural': 'Registros de Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
